services:
  - type: web
    name: bot-telegram-meli
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 bot.py"
    environment: python
    pythonVersion: "3.11"
